from __future__ import annotations

import argparse
import csv
import json
import time
from pathlib import Path

from hysys_automation import HysysCaseSession, HysysLaunchOptions


def get_value(prop, unit: str | None = None) -> float:
    if unit:
        return float(prop.GetValue(unit))
    return float(prop.Value)


def pressure_points(start: float, end: float, step: float) -> list[float]:
    if step <= 0:
        raise ValueError("--step-mpa must be positive")
    values: list[float] = []
    current = start
    while current <= end + step / 1_000_000:
        values.append(round(current, 9))
        current += step
    return values


def build_rows(args) -> tuple[list[dict], dict]:
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    case_path = output_dir / args.case_name
    if case_path.suffix.lower() != ".hsc":
        case_path = case_path.with_suffix(".hsc")

    rows: list[dict] = []
    with HysysCaseSession(HysysLaunchOptions(visible=args.visible)) as hysys:
        hysys_version = hysys.version
        hycase = hysys.create_case(
            case_path,
            "H2 density table",
            "Pure hydrogen density table generated by AI-HYSYS-Skill.",
        )
        hysys.configure_peng_robinson_basis(["Hydrogen"])
        stream = hysys.add_material_stream("H2", "Pure hydrogen stream")
        stream.ComponentMolarFraction.SetValues((1.0,))
        stream.Temperature.SetValue(float(args.temperature_c), "C")
        stream.MolarFlow.SetValue(float(args.molar_flow_kgmole_s), "kgmole/s")
        hysys.wait_for_solver_idle(timeout_s=args.solver_timeout_s)

        try:
            fluid_package = str(hycase.Flowsheet.FluidPackage.PropertyPackageName)
        except Exception:
            fluid_package = "PengRob"

        for pressure_mpa in pressure_points(args.start_mpa, args.end_mpa, args.step_mpa):
            if args.pressure_basis == "gauge":
                pressure_mpa_abs = pressure_mpa + args.atmospheric_pressure_mpa
                pressure_mpa_g = pressure_mpa
            else:
                pressure_mpa_abs = pressure_mpa
                pressure_mpa_g = pressure_mpa - args.atmospheric_pressure_mpa

            stream.Pressure.SetValue(pressure_mpa_abs * 1000.0, "kPa")
            stream.Temperature.SetValue(float(args.temperature_c), "C")
            hysys.wait_for_solver_idle(timeout_s=args.solver_timeout_s)

            density = get_value(stream.MassDensity, "kg/m3")
            if density <= 0 or density == -32767.0:
                raise RuntimeError(
                    f"HYSYS returned invalid density at {pressure_mpa} MPa({args.pressure_basis}): {density}"
                )

            rows.append(
                {
                    "pressure_MPa_table": pressure_mpa,
                    "pressure_basis": "MPa(g)" if args.pressure_basis == "gauge" else "MPa(a)",
                    "pressure_MPa_g": pressure_mpa_g,
                    "pressure_MPa_abs_used_by_HYSYS": pressure_mpa_abs,
                    "pressure_kPa_abs_used_by_HYSYS": get_value(stream.Pressure, "kPa"),
                    "temperature_C": get_value(stream.Temperature, "C"),
                    "density_HYSYS_kg_m3": density,
                    "compressibility_Z_HYSYS": get_value(stream.Compressibility),
                    "molar_density_HYSYS_kgmole_m3": get_value(stream.MolarDensity, "kgmole/m3"),
                    "vapour_fraction_HYSYS": get_value(stream.VapourFraction),
                    "solver_status": "OK",
                }
            )
        hysys.save_case()

    meta = {
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "hysys_version": hysys_version,
        "case_path": str(case_path),
        "calculation_basis": {
            "software": "Aspen HYSYS native COM automation",
            "property_package": "PengRob / Peng-Robinson",
            "fluid_package": fluid_package,
            "component": "Hydrogen",
            "composition_mole_fraction": {"Hydrogen": 1.0},
            "temperature_C": args.temperature_c,
            "pressure_basis_for_table": args.pressure_basis,
            "pressure_conversion": "P_abs_MPa = P_gauge_MPa + atmospheric_pressure_MPa",
            "atmospheric_pressure_MPa": args.atmospheric_pressure_mpa,
            "density_source": "HYSYS material stream MassDensity.GetValue('kg/m3')",
            "not_fitted": True,
        },
        "row_count": len(rows),
    }
    return rows, meta


def write_outputs(rows: list[dict], meta: dict, output_dir: Path, prefix: str) -> dict:
    csv_path = output_dir / f"{prefix}.csv"
    json_path = output_dir / f"{prefix}.json"
    log_path = output_dir / f"{prefix}_run_log.txt"

    with csv_path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    json_path.write_text(json.dumps({**meta, "rows": rows}, ensure_ascii=False, indent=2), encoding="utf-8")
    log_path.write_text(
        "\n".join(
            [
                f"{meta['created_at']}\tAspen HYSYS native hydrogen density table completed.",
                f"HYSYS version\t{meta['hysys_version']}",
                f"Case\t{meta['case_path']}",
                f"Pressure basis\t{meta['calculation_basis']['pressure_basis_for_table']}",
                f"Density source\t{meta['calculation_basis']['density_source']}",
                f"Rows\t{len(rows)}",
                f"First\t{rows[0]['pressure_MPa_table']} {rows[0]['pressure_basis']}, {rows[0]['density_HYSYS_kg_m3']:.9f} kg/m3",
                f"Last\t{rows[-1]['pressure_MPa_table']} {rows[-1]['pressure_basis']}, {rows[-1]['density_HYSYS_kg_m3']:.9f} kg/m3",
                f"CSV\t{csv_path}",
                f"JSON\t{json_path}",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    return {"csv": str(csv_path), "json": str(json_path), "run_log": str(log_path)}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a native HYSYS pure-hydrogen density table.")
    parser.add_argument("--start-mpa", type=float, default=1.0)
    parser.add_argument("--end-mpa", type=float, default=90.0)
    parser.add_argument("--step-mpa", type=float, default=1.0)
    parser.add_argument("--pressure-basis", choices=["absolute", "gauge"], default="absolute")
    parser.add_argument("--atmospheric-pressure-mpa", type=float, default=0.101325)
    parser.add_argument("--temperature-c", type=float, default=20.0)
    parser.add_argument("--molar-flow-kgmole-s", type=float, default=1.0)
    parser.add_argument("--solver-timeout-s", type=float, default=120.0)
    parser.add_argument("--visible", action="store_true")
    parser.add_argument(
        "--output-dir",
        default=str(Path("outputs") / f"hysys_h2_density_{time.strftime('%Y%m%d_%H%M%S')}"),
    )
    parser.add_argument("--case-name", default="hysys_h2_density_table.hsc")
    parser.add_argument("--prefix", default="h2_density_hysys_native")
    args = parser.parse_args()

    rows, meta = build_rows(args)
    outputs = write_outputs(rows, meta, Path(args.output_dir), args.prefix)
    print(json.dumps({**meta, "outputs": outputs}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
